# Generated by Django 5.0.3 on 2024-03-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
